---
- hosts: all
  roles:
    - base
    - ingress

- hosts: fedora
  roles:
    - cicd
    - monitoring
    - irc
    - carambolecomputer

- hosts: raspberry
  roles:
    - pihole
    - netboot
    - unify_proxy
    - home_assistant
