[tool.poetry]
name = "infrastructure"
version = "0.1.0"
description = "Ansible"
authors = ["René van Aerle <info@rvgate.nl>"]

[tool.poetry.dependencies]
python = "^3.12"
ansible = "^9.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
