---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      tlsSkipVerify: true
    isDefault: false
    version: 1
    readOnly: true