---
- name: run github runner container
  docker_container:
    name: "github-runner-{{ item }}"
    image: myoung34/github-runner:latest
    state: started
    restart_policy: always
    env:
      RUNNER_NAME_PREFIX: "{{ github.organisation }}-{{ item }}-"
      ACCESS_TOKEN: "{{ github.access_token }}"
      RUNNER_SCOPE: "org"
      DISABLE_AUTO_UPDATE: "true"
      ORG_NAME: "{{ github.organisation }}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      logging: enabled
      com.centurylinklabs.watchtower.enable: "true"
      # skip the update (exit 75) while the runner is executing a job
      com.centurylinklabs.watchtower.lifecycle.pre-update: "sh -c '! grep -qa \"[R]unner.Worker\" /proc/[0-9]*/cmdline || exit 75'"
      com.centurylinklabs.watchtower.lifecycle.pre-update-timeout: "1"
  loop: "{{ lookup('sequence', 'start=1 end=' + (github.runner_count | string)) | split(',') }}"


