---
- name: drone container
  docker_container:
    name: drone
    image: drone/drone:latest
    pull: yes
    state: started
    restart_policy: always
    volumes:
      - drone_data:/data
    env:
      DRONE_GITHUB_CLIENT_ID: "{{ drone_github_client_id }}"
      DRONE_GITHUB_CLIENT_SECRET: "{{ drone_github_client_secret }}"
      DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
      DRONE_SERVER_HOST: "{{ drone_server_host }}"
      DRONE_SERVER_PROTO: "https"
      DRONE_USER_CREATE: "{{ drone_user_create }}"
      DRONE_USER_FILTER: "{{ drone_user_filter }}"
      VIRTUAL_PORT: "80"
      VIRTUAL_HOST: "{{ drone_server_host }}"
  when: inventory_hostname in groups['servers']


- name: run drone docker runner
  docker_container:
    name: drone-runner
    image: drone/drone-runner-docker:latest
    pull: yes
    state: started
    restart_policy: always
    privileged: yes
    ports:
    - "3000:3000/tcp"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env:
      DRONE_RPC_PROTO: "https"
      DRONE_RPC_HOST: "{{ drone_server_host }}"
      DRONE_RPC_SECRET: "{{ drone_rpc_secret }}"
      DRONE_RUNNER_CAPACITY: "2"
      DRONE_RUNNER_NAME: "drone-runner"
      DRONE_DATADOG_ENABLED: "false"
