---
- name: run github runner container
  docker_container:
    name: "github-runner-{{ item }}"
    image: myoung34/github-runner:2.315.0
    state: started
    restart_policy: always
    env:
      RUNNER_NAME_PREFIX: "{{ github.organisation }}-{{ item }}-"
      ACCESS_TOKEN: "{{ github.access_token }}"
      RUNNER_SCOPE: "org"
      DISABLE_AUTO_UPDATE: "true"
      ORG_NAME: "{{ github.organisation }}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      logging: enabled
  loop: "{{ range(1, github.runner_count + 1) }}"
