---
- name: drone container
  docker_container:
    name: drone
    image: drone/drone:1
    pull: yes
    state: started
    restart_policy: always
    volumes:
      - drone_data:/data
    env:
      DRONE_GITHUB_CLIENT_ID: "{{ DRONE_GITHUB_CLIENT_ID }}"
      DRONE_GITHUB_CLIENT_SECRET: "{{ DRONE_GITHUB_CLIENT_SECRET }}"
      DRONE_RPC_SECRET: "{{ DRONE_RPC_SECRET }}"
      DRONE_SERVER_HOST: "{{ DRONE_SERVER_HOST }}"
      DRONE_SERVER_PROTO: "https"
      DRONE_USER_CREATE: "{{ DRONE_USER_CREATE }}"
      DRONE_USER_FILTER: "{{ DRONE_USER_FILTER }}"
      VIRTUAL_PORT: "80"
      VIRTUAL_HOST: "{{ DRONE_SERVER_HOST }}"
  when: inventory_hostname in groups['fedora']


- name: run drone docker runner
  docker_container:
    name: drone-runner
    image: drone/drone-runner-docker:1
    pull: yes
    state: started
    restart_policy: always
    privileged: yes
    ports:
    - "3000:3000/tcp"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env:
      DRONE_RPC_PROTO: "https"
      DRONE_RPC_HOST: "{{ DRONE_SERVER_HOST }}"
      DRONE_RPC_SECRET: "{{ DRONE_RPC_SECRET }}"
      DRONE_RUNNER_CAPACITY: "2"
      DRONE_RUNNER_NAME: "drone-runner"
      DRONE_DATADOG_ENABLED: "false"
