---
- name: create loki config directories
  file:
    path: /etc/loki
    state: directory
    mode: 0700

- name: copy loki config
  copy:
    src: loki-config.yaml
    dest: /etc/loki/loki-config.yaml

- name: create promtail config directories
  file:
    path: /etc/promtail
    state: directory
    mode: 0700

- name: copy promtail config
  copy:
    src: promtail-config.yaml
    dest: /etc/promtail/config.yml

- name: create prometheus config directories
  file:
    path: /etc/prometheus
    state: directory
    mode: 0700

- name: copy prometheus config
  copy:
    src: prometheus-config.yaml
    dest: /etc/prometheus/prometheus-config.yml
  register: prometheus_config

- name: create grafana config directories
  file:
    path: /var/lib/grafana/
    state: directory
    mode: 0700

- name: create grafana provisioning directory
  file:
    path: /etc/grafana/provisioning/
    state: directory
    mode: 0700

- name: copy grafana provisioning
  copy:
    src: grafana/provisioning/
    dest: /etc/grafana/provisioning/
