---
- name: create config directories
  file:
    path: /var/lib/grafana/
    state: directory
    mode: 0700

- name: create provisioning directory
  file:
    path: /etc/grafana/provisioning/
    state: directory
    mode: 0700

- name: copy provisioning
  copy:
    src: grafana/provisioning/
    dest: /etc/grafana/provisioning/

- name: grafana
  docker_container:
    name: monitoring-grafana
    image: grafana/grafana:latest
    pull: yes
    state: started
    restart_policy: unless-stopped
    user: 0
    volumes:
      - /var/lib/grafana:/var/lib/grafana
      - /etc/grafana/provisioning:/etc/grafana/provisioning
    env:
      VIRTUAL_HOST: "grafana.{{ domain }}"
      VIRTUAL_PORT: "3000"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_password }}"
      GF_DASHBOARDS_JSON_ENABLED: "true"
    networks:
      - name: monitoring
      - name: bridge
    labels:
      logging: enabled
  register: docker_grafana
