---
- name: create config directories
  file:
    path: /etc/loki
    state: directory
    mode: 0700

- name: copy loki config
  copy:
    src: loki-config.yaml
    dest: /etc/loki/loki-config.yaml

- name: loki
  docker_container:
    name: monitoring-loki
    image: grafana/loki:latest
    pull: yes
    state: started
    restart_policy: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - /etc/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - name: monitoring
    labels:
      logging: enabled
  register: docker_loki
