---
- name: run henrygd/beszel:latest container
  community.docker.docker_container:
    name: beszel
    image: henrygd/beszel:latest
    state: started
    restart_policy: unless-stopped
    detach: true
    env:
      VIRTUAL_HOST: "monitor.{{ domain }}"
      VIRTUAL_PORT: "8090"
      com.centurylinklabs.watchtower.enable: "true"