---
- name: node-exporter
  docker_container:
    name: monitoring-node-exporter
    image: prom/node-exporter:v1.7.0
    pull: yes
    state: started
    restart_policy: unless-stopped
    networks:
      - name: monitoring
    labels:
      logging: enabled

- name: cadvisor
  docker_container:
    name: monitoring-cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    pull: yes
    state: started
    restart_policy: unless-stopped
    privileged: true
    networks:
      - name: monitoring
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro