---
- name: include Ubuntu docker based installation
  include_tasks: docker-install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: include Raspbian docker based installation
  include_tasks: docker-install-raspbian.yml
  when: inventory_hostname in groups.raspberry

- name: include Fedora docker based installation
  include_tasks: docker-install-fedora.yml
  when: ansible_distribution == 'Fedora'

- name: generate portainer password
  ansible.builtin.shell:
    cmd: >
      htpasswd -nbB admin '{{ portainer_password }}'
      | cut -d ':' -f 2
      | xargs echo -n
      > ~/.portainer_password
    creates: ~/.portainer_password

- name: save generated password
  ansible.builtin.shell:
      cmd: cat ~/.portainer_password
  register: generated_portainer_password
  changed_when: False

- name: run portainer container
  docker_container:
    name: portainer
    image: portainer/portainer:latest
    pull: yes
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      VIRTUAL_HOST: "portainer.{{ domain }}"
      VIRTUAL_PORT: "9000"
    command: "--admin-password '{{ generated_portainer_password.stdout }}'"
    labels:
      logging: enabled

- name: run watchtower container
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: yes
    state: started
    restart_policy: always
    env:
      WATCHTOWER_SCHEDULE: "0 0 9 * * *" # 9 AM every day (Spring syntax)
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
