---
- name: install required debian docker packages
  apt:
    name: [
      'apt-transport-https',
      'ca-certificates',
      'software-properties-common',
    ]

- name: remove legacy docker apt repository
  file:
    path: /etc/apt/sources.list.d/download_docker_com_linux_raspbian.list
    state: absent

- name: add docker apt repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/raspbian
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: https://download.docker.com/linux/raspbian/gpg
    state: present
  register: docker_repository

- name: update apt cache
  apt:
    update_cache: true
  when: docker_repository.changed

- name: install docker
  apt:
    name: "{{ item }}"
    install_recommends: False
  with_items:
    - docker-ce
    - docker-compose
    - docker-compose-plugin

- name: pip packages
  apt:
    name: python3-docker