---
- name: nginx default page
  docker_container:
    name: default
    image: nginx
    state: started
    restart_policy: always
    env:
      VIRTUAL_HOST: "{{ domain }}"

- name: nginx ingest
  docker_container:
    name: ingest
    image: nginxproxy/nginx-proxy
    state: started
    restart_policy: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/certs:/etc/nginx/certs
    env:
      DEFAULT_HOST: "{{ domain }}"
    labels:
      filebeat: "enabled"

- name: reload ingest container daily
  cron:
    name: reload ingest nginx for certificates
    special_time: daily
    job: /usr/bin/docker exec -it ingest nginx -s reload > /dev/null
