---
- name: create tmp docker directories
  file:
    path: /srv/docker/nginx-ingest
    state: directory

- name: upload nginx dockerfile
  tags: build
  template:
    src: nginx-ingest.Dockerfile
    dest: /srv/docker/nginx-ingest/Dockerfile

- name: build nginx ingest container
  docker_image:
    build:
      pull: yes
      path: /srv/docker/nginx-ingest/
    name: nginx-ingest
    tag: latest
    source: build
    force_absent: yes
    force_tag: yes
    force_source: yes
    state: present

- name: run nginx ingest container
  docker_container:
    name: nginx-ingest
    image: nginx-ingest:latest
    state: started
    restart_policy: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/etc/letsencrypt/live/nginx:/etc/nginx/certs"
    env:
      DEFAULT_HOST: "{{ domain }}"

- name: restart ingest container weekly
  cron:
    name: restart ingest to reload certificates
    special_time: weekly
    job: "/usr/bin/docker restart nginx-ingest > /dev/null"
