---
- name: system packages
  package:
    name: [
      'curl',
      'git',
      'htop',
      'iftop',
      'iotop',
      'nload',
      'nmap',
      'python',
      'python-pip',
      'screen',
      'telnet',
      'tig',
      'traceroute',
      'tree',
      'unzip',
      'vim',
      'virtualenv',
      'whois',
    ]
    state: present

- name: install fedora specific packages
  dnf:
    name: [
      'crontabs',
      'dnf-plugins-core',
      'httpd-tools',
    ]
  when: ansible_distribution == 'Fedora'

- name: install debian specific packages
  apt:
    name: [
      'apache2-utils',
      'cron',
    ]
  when: ansible_distribution == 'Debian'