---
- name: install fedora specific packages
  dnf:
    name: [
        'crontabs',
        'dnf-plugins-core',
        'fuse',
        'httpd-tools',
        'kernel-modules',
        'squashfuse',
    ]
  when: ansible_distribution == 'Fedora'

- name: install debian specific packages
  apt:
    name: [
        'apache2-utils',
        'cron',
        'dnsutils',
    ]
  when: ansible_distribution == 'Debian'

- name: system packages
  package:
    name: [
      'curl',
      'git',
      'htop',
      'iftop',
      'iotop',
      'neofetch',
      'net-tools',
      'nload',
      'nmap',
      'python',
      'python-pip',
      'screen',
      'snapd',
      'telnet',
      'tig',
      'traceroute',
      'tree',
      'unzip',
      'vim',
      'virtualenv',
      'whois',
    ]
    state: present

- name: snap packages
  community.general.snap:
    name:
      - core
  register: snap_core

- name: snap refresh core
  command: "snap refresh core"
  when: snap_core.changed

- name: symlink snap
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
    force: yes
  when: ansible_distribution == 'Fedora'