---
- name: run pihole container
  docker_container:
    name: dns-sinkhole
    image: pihole/pihole:latest
    state: started
    restart_policy: always
    pull: yes
    ports:
      - "53:53/udp"
    volumes:
      - "pihole-dnsmasq:/etc/dnsmasq.d"
      - "pihole-etc:/etc/pihole"
    env:
      WEBPASSWORD: "{{ pihole_password }}"
      DNS1: "8.8.8.8"
      DNS2: "8.8.4.4"
      ServerIP: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      VIRTUAL_PORT: "80"
      VIRTUAL_HOST: "pihole.{{ domain }}"